server:
  port: 10010   #配置端口号
spring:
  application:
    name: gateway    #服务名称
  cloud:
    nacos:
      server-addr: http://localhost:8848   #Nacos地址
    gateway:
      routes:    #网关路由配置
        - id: user-service    #路由id,自定义,只要唯一即可
          uri: lb://userservice    #lb = loadbalance负载均衡, 意思为userservice进行负载均衡
          predicates:   #路由断言, 也就是判断请求是否符合路由规则的条件
            - Path=/user/**    #路径匹配规则, 只要以/user/开头均路由到lb:userservice
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**