server:
  port: 10010   #配置端口号
spring:
  application:
    name: gateway    #服务名称
  cloud:
    nacos:
      server-addr: http://localhost:8848   #Nacos地址
    gateway:
      routes:    #网关路由配置
        - id: user-service    #路由id,自定义,只要唯一即可
          uri: lb://userservice    #lb = loadbalance负载均衡, 意思为userservice进行负载均衡
          predicates:   #路由断言, 也就是判断请求是否符合路由规则的条件
            - Path=/user/**    #路径匹配规则, 只要以/user/开头均路由到lb:userservice
#          filters:
#            - AddRequestHeader=truth,Itcast is freaking awesome
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
            - After=1970-01-20T17:42:47.789-07:00[America/Denver]
      default-filters:
        - AddRequestHeader=truth,Itcast is freaking awesome
        - RemoveRequestHeader=truth
    globalcors:
      add-to-simple-url-handler-mapping: true    #解决options请求被拦截问题
      corsConfigurations:
        '[/*]':    #针对所有路径均做跨域处理
          allowedOtigins:   #允许跨域的网站
            - "http://localhost:8090"
            - "http://www.leyou.com"
          allowedMethod:    #允许跨域请求的请求方法
            - "GET"
            - "POST"
            - "DELETE"
            - "PUT"
            - "OPTIONS"
          allowedHeaders: "*"   #允许在请求头中携带的头信息, 这里是所有均允许
          allowCredentials: true    #是否允许携带cookie
          maxAge: 360000    #这次跨域检测的有效期