server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://119.45.11.101:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: orderservice
#  cloud:
#    nacos:
#      server-addr: http://localhost:80 # nacos 服务端地址
#      discovery:
#        cluster-name: shanghai
#        namespace: f40b217c-98ba-452e-9bc3-548707c8dc2c # 命名空间，填ID
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
ribbon:
  eager-load:
    enabled: true
    clients:
      - userservice